### ISSUE TITLE
Error for Chaturbate

### ISSUE THREAD

**Issue by rytyson** [SagalVanderklok/ChatRoomRecorder#44]
Receiving error for all chaturbate rooms. Log shows: status, then playlist, resolutions just has a dash (other sites have the resolutions available), and then  "error occurred - value does not fall within the expected range"

Other sites are working fine.

![Image](https://github.com/user-attachments/assets/51f7c73d-9e7a-41fa-9144-24a1bd8dcf31)

**Comment by dwa99** [comment]
I got the same messages, all rooms from Chaturbate report this error

**Comment by SagalVanderklok** [comment]
What settings do you use? How many chat rooms are recorded?

**Comment by SagalVanderklok** [comment]
I was able to reproduce the error. It looks like they changed playlist location

**Comment by dwa99** [comment]
Concurrent updates set to 1, Update delay 15, Update interval 60, monitored 11 channels, max number of channels recorded at once 5-6.

**Comment by SagalVanderklok** [comment]
The problem is fixed in v1.6.7

**Comment by rytyson** [comment]
Thank you!

**Comment by BKA1990** [comment]
Thanks but Still getting URL is incorrect, even with the latest version

**Comment by SagalVanderklok** [comment]
What URL are you entering?

**Comment by BKA1990** [comment]
https://chaturbate.com/killer_in_you_/

**Comment by SagalVanderklok** [comment]
I've just added it without problems. Is this happening with other sites or rooms?

**Comment by BKA1990** [comment]
Yes it is, what version of streamlink are you using?

**Comment by SagalVanderklok** [comment]
I use Streamlink 7.1.2, but It's not related to Streamlink. This error occurs on URL parsing. What's your system language?

**Comment by BKA1990** [comment]
I can manually create a text file add thee url to it then open it using the app, that works, but adding the url directly to the app is not working.

**Comment by SagalVanderklok** [comment]
Are you adding URLs from the web browser? What if you paste a URL into Notepad and then copy it from there?

**Comment by BKA1990** [comment]
No I create a notepad file i add the URL's copied fro;m the browser then i save it and i use this button 

![Image](https://github.com/user-attachments/assets/573239dd-d8fc-4b51-8d34-a3a6257edd1c) To open it and it adds all the URLs at once then i can see them and i can recored

**Comment by SagalVanderklok** [comment]
Try to paste a URL into Notepad and then copy it from there into the application (just a single URL and without saving a file)

**Comment by BKA1990** [comment]
The same error...

**Comment by dwa99** [comment]
@SagalVanderklok, thanks! now works again. 

Could you clarify what 'Update delay' and 'Update interval' do. ie, default settings: 1 concurrent update per 60 sec and then 15 sec delay between of  ... ?

**Comment by SagalVanderklok** [comment]
> The same error...

I have some ideas. I'll build a test release so you can check if it helps

**Comment by SagalVanderklok** [comment]
> [@SagalVanderklok](https://github.com/SagalVanderklok), thanks! now works again.
> 
> Could you clarify what 'Update delay' and 'Update interval' do. ie, default settings: 1 concurrent update per 60 sec and then 15 sec delay between of ... ?

Chat rooms update in cycles and update cycles perform in intervals whose length are defined by "Update Intervals" setting. But during the update cycle each chat room updates with a random delay from the interval from 0 to "Update delay" seconds (in order to avoid sending multiple requests to a web server simultaneously)

**Comment by SagalVanderklok** [comment]
@dwa99, try v.1.6.8

**Comment by dwa99** [comment]
two additional questions, will you plan to add an export/import option of the rooms list , and release Linux version ?

**Comment by SagalVanderklok** [comment]
> two additional questions, will you plan to add an export/import option of the rooms list , and release Linux version ?

Import and export features are already implemented. You can import chat rooms via text file and export them by copying their URLs in the chat rooms list
There are currently no plans to release a version for Linux

**Comment by SagalVanderklok** [comment]
Did you test v1.6.8?

**Comment by dwa99** [comment]
Nope, I run 1.6.7 all rooms works. It was @BKA1990 who was getting still error .What did you changed in v1.6.8? the description is 'for tests'.

**Comment by SagalVanderklok** [comment]
It's a temporary release. I modified function that parse URL. There'no other changes there
@BKA1990 , did you test v1.6.8?

**Comment by BKA1990** [comment]
No not really @SagalVanderklok , i gave up but it is working as i said just need to add the URLs to the favorite list file manually.
And now i started to create a mew software using python so far so good, if you would like to collaborate any help is welcome!
Thanks a lot for the effort btw!

**Comment by SagalVanderklok** [comment]
@BKA1990 Could you please try to add a URL in v1.6.8? I can't reproduce the error, but other users can also encounter this problem

**Comment by BKA1990** [comment]
@SagalVanderklok yes it is working now, thank you!

**Comment by SagalVanderklok** [comment]
Great! I'm gonna build a permanent release. Thanks!
